import { Footer, Header} from "@/components/LayoutExpo";
import type { Metadata } from "next";

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default async function Layout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <>
    <div className="overflow-x-hidden">
      <Header locale={locale} />
      {children}
      <Footer locale={locale} />

    </div>
    </>
  );
}
